"use client";

import { AppShell } from "@/components/app-shell";
import { api } from "@/lib/api";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Item = { id: number; name: string; code: string; groupName?: string | null; sizeType?: string | null; active: boolean };
type Config = { title: string; singular: string; endpoint: string; extraField?: "groupName" | "sizeType"; extraLabel?: string };
const initialForm = { name: "", code: "", groupName: "", sizeType: "" };

export function MasterDataPage({ config }: { config: Config }) {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [form, setForm] = useState(initialForm); const [editing, setEditing] = useState<Item | null>(null); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const response = await api.get<Item[]>(config.endpoint); setItems(response.data); } catch { setError("Unable to load master data. Ensure the backend is running."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [config.endpoint]);
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const openCreate = () => { setEditing(null); setForm(initialForm); setShowForm(true); };
  const openEdit = (item: Item) => { setEditing(item); setForm({ name: item.name, code: item.code, groupName: item.groupName ?? "", sizeType: item.sizeType ?? "" }); setShowForm(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, [config.extraField ?? "groupName"]: config.extraField ? form[config.extraField] : null }; if (editing) await api.put(`${config.endpoint}/${editing.id}`, payload); else await api.post(config.endpoint, payload); setShowForm(false); await load(); } catch { setError("Unable to save. Check that the code is unique and all required fields are complete."); } finally { setSaving(false); } };
  const toggle = async (item: Item) => { if (!window.confirm(`${item.active ? "Deactivate" : "Activate"} ${item.name}?`)) return; try { await api.patch(`${config.endpoint}/${item.id}/active`, { active: !item.active }); await load(); } catch { setError("Unable to update status."); } };
  return <AppShell><section className="mx-auto max-w-6xl p-5 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">Masters</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">{config.title}</h1></div><button onClick={openCreate} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800">Add {config.singular}</button></div>
    <div className="mt-7 rounded-lg border bg-card shadow-sm"><div className="border-b p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}...`} className="w-full rounded-md border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-slate-300" /></div>{error && <p className="m-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {loading ? <p className="p-6 text-sm text-muted-foreground">Loading {config.title.toLowerCase()}...</p> : filtered.length === 0 ? <p className="p-6 text-sm text-muted-foreground">No {config.title.toLowerCase()} found. Add your first item to get started.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Name</th><th className="px-5 py-3 font-medium">Code</th>{config.extraField && <th className="px-5 py-3 font-medium">{config.extraLabel}</th>}<th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium text-right">Actions</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t"><td className="px-5 py-3 font-medium">{item.name}</td><td className="px-5 py-3">{item.code}</td>{config.extraField && <td className="px-5 py-3">{item[config.extraField]}</td>}<td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${item.active ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-600"}`}>{item.active ? "Active" : "Inactive"}</span></td><td className="space-x-3 px-5 py-3 text-right"><button onClick={() => openEdit(item)} className="text-slate-700 hover:underline">Edit</button><button onClick={() => void toggle(item)} className="text-slate-700 hover:underline">{item.active ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div>}</div>
    {showForm && <div className="fixed inset-0 z-10 grid place-items-center bg-slate-950/30 p-4"><form onSubmit={save} className="w-full max-w-md rounded-lg bg-card p-6 shadow-xl"><h2 className="text-lg font-semibold">{editing ? `Edit ${config.singular}` : `Add ${config.singular}`}</h2><div className="mt-5 space-y-4"><Field label="Name" value={form.name} onChange={(name) => setForm({ ...form, name })} /><Field label="Code" value={form.code} onChange={(code) => setForm({ ...form, code })} />{config.extraField && <Field label={config.extraLabel ?? config.extraField} value={form[config.extraField]} onChange={(value) => setForm({ ...form, [config.extraField!]: value })} />}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowForm(false)} className="rounded-md border px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-md bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{saving ? "Saving..." : "Save"}</button></div></form></div>}</section></AppShell>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium">{label}<input required value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2 font-normal outline-none focus:ring-2 focus:ring-slate-300" /></label>; }
