CREATE TABLE marketplaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    default_commission_rate NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (default_commission_rate >= 0),
    default_shipping_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (default_shipping_charge >= 0),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_marketplaces_active ON marketplaces (active);

INSERT INTO marketplaces (name, code, active, default_commission_rate, default_shipping_charge, remarks) VALUES
    ('Meesho', 'MEESHO', TRUE, 0, 0, 'Meesho marketplace'),
    ('Amazon', 'AMAZON', TRUE, 0, 0, 'Amazon India marketplace'),
    ('Flipkart', 'FLIPKART', TRUE, 0, 0, 'Flipkart marketplace'),
    ('Own Website', 'WEBSITE', TRUE, 0, 0, 'Direct website sales'),
    ('Other', 'OTHER', TRUE, 0, 0, 'Other sales channels');

ALTER TABLE orders ADD COLUMN marketplace_id BIGINT REFERENCES marketplaces(id);

UPDATE orders
SET marketplace_id = marketplaces.id
FROM marketplaces
WHERE marketplaces.code = orders.platform;

ALTER TABLE orders ALTER COLUMN marketplace_id SET NOT NULL;

ALTER TABLE orders DROP CONSTRAINT uq_orders_platform_order_id;
ALTER TABLE orders DROP COLUMN platform;
ALTER TABLE orders ADD CONSTRAINT uq_orders_marketplace_order_id UNIQUE (marketplace_id, order_id);

CREATE INDEX idx_orders_marketplace_id ON orders (marketplace_id);

ALTER TABLE settlements ADD COLUMN marketplace_id BIGINT REFERENCES marketplaces(id);

UPDATE settlements
SET marketplace_id = marketplaces.id
FROM marketplaces
WHERE marketplaces.code = settlements.platform;

ALTER TABLE settlements ALTER COLUMN marketplace_id SET NOT NULL;

ALTER TABLE settlements DROP COLUMN platform;

DROP INDEX IF EXISTS idx_settlements_platform;
CREATE INDEX idx_settlements_marketplace_id ON settlements (marketplace_id);
