CREATE TABLE product_variant_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    previous_selling_price NUMERIC(12,2) NOT NULL CHECK(previous_selling_price >= 0),
    new_selling_price NUMERIC(12,2) NOT NULL CHECK(new_selling_price >= 0),
    effective_date DATE NOT NULL,
    remarks TEXT,
    recorded_by_user_id BIGINT,
    recorded_by_user_name VARCHAR(150),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_variant_price_history_variant_effective_date
    ON product_variant_price_history(variant_id, effective_date DESC, created_at DESC);
