CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    group_name VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    size_type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_brands_active ON brands (active);
CREATE INDEX idx_categories_active ON categories (active);
CREATE INDEX idx_colors_active ON colors (active);
CREATE INDEX idx_sizes_active ON sizes (active);

INSERT INTO categories (name, code, group_name) VALUES
    ('Men''s T-Shirt', 'MTS', 'MEN'), ('Men''s Shirt', 'MSH', 'MEN'),
    ('Men''s Hoodie', 'MHD', 'MEN'), ('Men''s Sweatshirt', 'MSW', 'MEN'),
    ('Men''s Polo', 'MPL', 'MEN'), ('Men''s Jogger', 'MJG', 'MEN'),
    ('Men''s Shorts', 'MSHO', 'MEN'), ('Men''s Jeans', 'MJN', 'MEN'),
    ('Ladies Top', 'LTP', 'WOMEN'), ('Ladies Kurti', 'LKT', 'WOMEN'),
    ('Ladies Suit Set', 'LSS', 'WOMEN'), ('Ladies Frock', 'LFK', 'WOMEN'),
    ('Ladies Co-ord Set', 'LCS', 'WOMEN'), ('Ladies Blouse', 'LBL', 'WOMEN'),
    ('Dupatta', 'LDP', 'WOMEN'), ('Saree', 'LSR', 'WOMEN');

INSERT INTO colors (name, code) VALUES
    ('Black', 'BLK'), ('White', 'WHT'), ('Navy', 'NVY'), ('Olive', 'OLV'),
    ('Beige', 'BEG'), ('Grey', 'GRY'), ('Red', 'RED'), ('Blue', 'BLU'),
    ('Pink', 'PNK'), ('Green', 'GRN'), ('Yellow', 'YLW'), ('Maroon', 'MRN');

INSERT INTO sizes (name, code, size_type) VALUES
    ('XS', 'XS', 'APPAREL'), ('S', 'S', 'APPAREL'), ('M', 'M', 'APPAREL'),
    ('L', 'L', 'APPAREL'), ('XL', 'XL', 'APPAREL'), ('XXL', 'XXL', 'APPAREL'),
    ('XXXL', 'XXXL', 'APPAREL');
