CREATE SEQUENCE product_design_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_number BIGINT NOT NULL UNIQUE,
    product_name VARCHAR(200) NOT NULL,
    brand_id BIGINT NOT NULL REFERENCES brands(id),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    description TEXT,
    fabric VARCHAR(100), fit VARCHAR(100), neck_type VARCHAR(100), sleeve_type VARCHAR(100),
    gender VARCHAR(30), sourcing_type VARCHAR(20) NOT NULL, product_cost NUMERIC(12,2) NOT NULL,
    selling_price NUMERIC(12,2) NOT NULL, mrp NUMERIC(12,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_product_prices CHECK (product_cost >= 0 AND selling_price >= 0 AND mrp >= 0)
);
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id), color_id BIGINT NOT NULL REFERENCES colors(id), size_id BIGINT NOT NULL REFERENCES sizes(id),
    sku VARCHAR(100) NOT NULL UNIQUE, cost_price NUMERIC(12,2) NOT NULL, selling_price NUMERIC(12,2) NOT NULL, mrp NUMERIC(12,2) NOT NULL,
    reorder_level INTEGER NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_variant_combination UNIQUE (product_id, color_id, size_id),
    CONSTRAINT chk_variant_prices CHECK (cost_price >= 0 AND selling_price >= 0 AND mrp >= 0 AND reorder_level >= 0)
);
CREATE INDEX idx_products_brand_id ON products(brand_id); CREATE INDEX idx_products_category_id ON products(category_id); CREATE INDEX idx_variants_product_id ON product_variants(product_id);
