CREATE TABLE inventory_transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, variant_id BIGINT NOT NULL REFERENCES product_variants(id),
 transaction_type VARCHAR(30) NOT NULL, quantity INTEGER NOT NULL CHECK(quantity>0), unit_cost NUMERIC(12,2) CHECK(unit_cost>=0),
 reference_type VARCHAR(50), reference_id VARCHAR(100), notes TEXT, transaction_date DATE NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_inventory_transactions_variant_id ON inventory_transactions(variant_id);
CREATE INDEX idx_inventory_transactions_date ON inventory_transactions(transaction_date);
