CREATE TABLE return_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    order_item_id BIGINT NOT NULL REFERENCES order_items(id),
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    return_type VARCHAR(20) NOT NULL CHECK (return_type IN ('RETURNED', 'RTO')),
    reason VARCHAR(500) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    product_cost NUMERIC(12,2) NOT NULL CHECK (product_cost >= 0),
    shipping_loss NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_loss >= 0),
    other_loss NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (other_loss >= 0),
    total_loss NUMERIC(12,2) NOT NULL CHECK (total_loss >= 0),
    resellable BOOLEAN NOT NULL,
    return_status VARCHAR(20) NOT NULL DEFAULT 'INITIATED' CHECK (return_status IN ('INITIATED', 'RECEIVED', 'INSPECTED', 'COMPLETED')),
    return_date DATE NOT NULL,
    received_date DATE,
    remarks TEXT,
    inventory_restored BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_return_records_received_date CHECK (received_date IS NULL OR received_date >= return_date)
);

CREATE INDEX idx_return_records_order ON return_records(order_id);
CREATE INDEX idx_return_records_order_item ON return_records(order_item_id);
CREATE INDEX idx_return_records_variant ON return_records(variant_id);
CREATE INDEX idx_return_records_type_status ON return_records(return_type, return_status);
CREATE INDEX idx_return_records_date ON return_records(return_date);
