CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id VARCHAR(100) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    settlement_date DATE NOT NULL,
    settlement_period_start DATE NOT NULL,
    settlement_period_end DATE NOT NULL,
    gross_amount NUMERIC(12,2) NOT NULL CHECK (gross_amount >= 0),
    marketplace_fees NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (marketplace_fees >= 0),
    shipping_charges NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_charges >= 0),
    return_charges NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (return_charges >= 0),
    other_charges NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (other_charges >= 0),
    net_amount NUMERIC(12,2) NOT NULL CHECK (net_amount >= 0),
    received_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (received_amount >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'UNMATCHED',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_settlements_settlement_id UNIQUE (settlement_id),
    CONSTRAINT chk_settlements_period CHECK (settlement_period_end >= settlement_period_start)
);

CREATE INDEX idx_settlements_platform ON settlements (platform);
CREATE INDEX idx_settlements_status ON settlements (status);
CREATE INDEX idx_settlements_reconciliation_status ON settlements (reconciliation_status);
CREATE INDEX idx_settlements_settlement_date ON settlements (settlement_date);

CREATE TABLE settlement_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_id_snapshot VARCHAR(100) NOT NULL,
    order_date_snapshot DATE NOT NULL,
    gross_order_amount NUMERIC(12,2) NOT NULL CHECK (gross_order_amount >= 0),
    marketplace_fee NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (marketplace_fee >= 0),
    shipping_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_charge >= 0),
    return_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (return_charge >= 0),
    other_charge NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (other_charge >= 0),
    expected_net_settlement NUMERIC(12,2) NOT NULL CHECK (expected_net_settlement >= 0),
    settled_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (settled_amount >= 0),
    difference NUMERIC(12,2) NOT NULL,
    reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'UNMATCHED',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settlement_items_settlement FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE CASCADE,
    CONSTRAINT fk_settlement_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT uq_settlement_items_order UNIQUE (order_id)
);

CREATE INDEX idx_settlement_items_settlement_id ON settlement_items (settlement_id);
CREATE INDEX idx_settlement_items_reconciliation_status ON settlement_items (reconciliation_status);
