package com.ecommerce.commerceapi.products.service;
import com.ecommerce.commerceapi.masters.domain.*; import com.ecommerce.commerceapi.masters.repository.*; import com.ecommerce.commerceapi.products.api.*; import com.ecommerce.commerceapi.products.domain.*; import com.ecommerce.commerceapi.products.repository.*; import jakarta.persistence.*; import java.util.*; import java.util.stream.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ProductService {
 private final ProductRepository products; private final BrandRepository brands; private final CategoryRepository categories; private final ColorRepository colors; private final SizeRepository sizes; @PersistenceContext private EntityManager entityManager;
 public ProductService(ProductRepository products,BrandRepository brands,CategoryRepository categories,ColorRepository colors,SizeRepository sizes){this.products=products;this.brands=brands;this.categories=categories;this.colors=colors;this.sizes=sizes;}
 @Transactional(readOnly=true) public List<ProductResponse> findAll(){return products.findAll().stream().map(this::response).toList();} @Transactional(readOnly=true) public ProductResponse findById(Long id){return response(products.findWithDetailsById(id).orElseThrow(()->new EntityNotFoundException("Product not found")));}
 @Transactional public ProductResponse create(ProductRequest request){ Brand brand=active(brands.findById(request.brandId()).orElseThrow(()->new EntityNotFoundException("Brand not found")),"Brand"); Category category=active(categories.findById(request.categoryId()).orElseThrow(()->new EntityNotFoundException("Category not found")),"Category"); List<Color> selectedColors=activeColors(request.colorIds()); List<Size> selectedSizes=activeSizes(request.sizeIds()); Product product=new Product(); apply(product,request,brand,category); product.setDesignNumber(((Number)entityManager.createNativeQuery("SELECT nextval('product_design_number_seq')").getSingleResult()).longValue()); for(Color color:selectedColors) for(Size size:selectedSizes){ ProductVariant variant=new ProductVariant(); variant.setProduct(product); variant.setColor(color); variant.setSize(size); variant.setSku(brand.getCode()+"-"+category.getCode()+"-"+String.format("%04d",product.getDesignNumber())+"-"+color.getCode()+"-"+size.getCode()); variant.setCostPrice(request.productCost()); variant.setSellingPrice(request.sellingPrice()); variant.setMrp(request.mrp()); variant.setReorderLevel(Optional.ofNullable(request.reorderLevel()).orElse(0)); product.getVariants().add(variant); } return response(products.save(product)); }
 @Transactional public ProductResponse update(Long id,ProductRequest request){ Product product=products.findWithDetailsById(id).orElseThrow(()->new EntityNotFoundException("Product not found")); Brand brand=active(brands.findById(request.brandId()).orElseThrow(()->new EntityNotFoundException("Brand not found")),"Brand"); Category category=active(categories.findById(request.categoryId()).orElseThrow(()->new EntityNotFoundException("Category not found")),"Category"); if(!product.getBrand().getId().equals(brand.getId())||!product.getCategory().getId().equals(category.getId())) throw new IllegalArgumentException("Brand and category cannot be changed after SKU creation"); apply(product,request,brand,category); return response(product); }
 @Transactional public ProductResponse updateStatus(Long id,ProductStatus status){Product product=products.findById(id).orElseThrow(()->new EntityNotFoundException("Product not found"));product.setStatus(status);return response(product);}
 private void apply(Product p,ProductRequest r,Brand b,Category c){p.setProductName(r.productName().trim());p.setBrand(b);p.setCategory(c);p.setDescription(r.description());p.setFabric(r.fabric());p.setFit(r.fit());p.setNeckType(r.neckType());p.setSleeveType(r.sleeveType());p.setGender(r.gender());p.setSourcingType(r.sourcingType());p.setProductCost(r.productCost());p.setSellingPrice(r.sellingPrice());p.setMrp(r.mrp());}
 private List<Color> activeColors(List<Long> ids){if(new HashSet<>(ids).size()!=ids.size())throw new IllegalArgumentException("Colors must be unique");List<Color> result=colors.findAllById(ids);if(result.size()!=ids.size()||result.stream().anyMatch(v->!v.isActive()))throw new IllegalArgumentException("All selected colors must exist and be active");return result;} private List<Size> activeSizes(List<Long> ids){if(new HashSet<>(ids).size()!=ids.size())throw new IllegalArgumentException("Sizes must be unique");List<Size> result=sizes.findAllById(ids);if(result.size()!=ids.size()||result.stream().anyMatch(v->!v.isActive()))throw new IllegalArgumentException("All selected sizes must exist and be active");return result;} private <T extends MasterDataEntity>T active(T item,String label){if(!item.isActive())throw new IllegalArgumentException(label+" must be active");return item;}
 private ProductResponse response(Product p){return new ProductResponse(p.getId(),String.format("%04d",p.getDesignNumber()),p.getProductName(),p.getBrand().getId(),p.getBrand().getName(),p.getCategory().getId(),p.getCategory().getName(),p.getSourcingType().name(),p.getProductCost(),p.getSellingPrice(),p.getMrp(),p.getStatus().name(),p.getCreatedAt(),p.getVariants().stream().map(v->new VariantResponse(v.getId(),v.getSku(),v.getColor().getId(),v.getColor().getName(),v.getSize().getId(),v.getSize().getName(),v.getCostPrice(),v.getSellingPrice(),v.getMrp(),v.getReorderLevel(),v.isActive())).toList());}
}
