package com.ecommerce.commerceapi.products.domain;
import com.ecommerce.commerceapi.masters.domain.Brand; import com.ecommerce.commerceapi.masters.domain.Category; import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Entity @Table(name="products") public class Product {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="design_number",nullable=false,unique=true) private Long designNumber; @Column(name="product_name",nullable=false) private String productName;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="brand_id",nullable=false) private Brand brand; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="category_id",nullable=false) private Category category;
 private String description,fabric,fit,neckType,sleeveType,gender; @Enumerated(EnumType.STRING) @Column(nullable=false) private SourcingType sourcingType; @Column(nullable=false) private BigDecimal productCost,sellingPrice,mrp; @Enumerated(EnumType.STRING) @Column(nullable=false) private ProductStatus status=ProductStatus.ACTIVE; @Column(nullable=false,updatable=false) private Instant createdAt; @Column(nullable=false) private Instant updatedAt;
 @OneToMany(mappedBy="product",cascade=CascadeType.ALL,orphanRemoval=true) private List<ProductVariant> variants=new ArrayList<>(); @PrePersist void create(){createdAt=updatedAt=Instant.now();} @PreUpdate void update(){updatedAt=Instant.now();}
 public Long getId(){return id;} public Long getDesignNumber(){return designNumber;} public void setDesignNumber(Long v){designNumber=v;} public String getProductName(){return productName;} public void setProductName(String v){productName=v;} public Brand getBrand(){return brand;} public void setBrand(Brand v){brand=v;} public Category getCategory(){return category;} public void setCategory(Category v){category=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public String getFabric(){return fabric;} public void setFabric(String v){fabric=v;} public String getFit(){return fit;} public void setFit(String v){fit=v;} public String getNeckType(){return neckType;} public void setNeckType(String v){neckType=v;} public String getSleeveType(){return sleeveType;} public void setSleeveType(String v){sleeveType=v;} public String getGender(){return gender;} public void setGender(String v){gender=v;} public SourcingType getSourcingType(){return sourcingType;} public void setSourcingType(SourcingType v){sourcingType=v;} public BigDecimal getProductCost(){return productCost;} public void setProductCost(BigDecimal v){productCost=v;} public BigDecimal getSellingPrice(){return sellingPrice;} public void setSellingPrice(BigDecimal v){sellingPrice=v;} public BigDecimal getMrp(){return mrp;} public void setMrp(BigDecimal v){mrp=v;} public ProductStatus getStatus(){return status;} public void setStatus(ProductStatus v){status=v;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;} public List<ProductVariant> getVariants(){return variants;}
}
